stages:
  - install
  - build

variables:
  TRION_CLI_VERSION: 12.2.4

#
#jobs
#

install:
  stage: install
  image: trion/ng-cli:${TRION_CLI_VERSION}
  script:
    - npm ci
  only:
    changes:
      - package-lock.json

build:
  stage: build
  extends: .install
  image: trion/ng-cli-karma:${TRION_CLI_VERSION}
  script:
    - npm run lint
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/softmodem-ngx
