version: '3.4'

services:

  backend:
    container_name: api.dev
    image: registry.gitlab.com/lsd5/backend/dev:latest
    pull_policy: always
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
      - 9229:9229
    command:
      [
        'node',
        '--inspect=0.0.0.0:9229',
        '-r',
        'module-alias/register',
        'dist/main.js'
      ]

  frontend:
    container_name: ngx.dev
    image: registry.gitlab.com/lsd5/ngx/dev:latest
    pull_policy: always
    # build:

    #   context: .

    #   dockerfile: ./Dockerfile
    environment:
      - PORT=80
    ports:
      - 80:80
    # DO NOT USE command : the Dockerfile CMD must be called in order to replace $PORT with sed


  mongo:
    container_name: db.dev
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=dev
    ports:
      - 27017:27017
    command: mongod
